spring:
  cloud:
    stream:
      bindings:
        userProcessor-in-0.destination: user-in
        userProcessor-out-0.destination: user-out
      kafka:
        streams:
          binder:
            applicationId: my-app
            brokers: localhost:9092
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.springframework.kafka.support.serializer.JsonSerde
              spring:
                json:
                  key:
                    default:
                      type: java.lang.String
                  value:
                    default:
                      type: com.techboss.kafka.model.User